# Generated by Django 4.2.6 on 2023-10-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cost",
            field=models.IntegerField(verbose_name="Book Price $"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(verbose_name="Book Description"),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Book Name"),
        ),
    ]
