# Generated by Django 4.2.6 on 2023-11-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ProductCL", "0001_initial"),
        ("CustomerCL", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.IntegerField(verbose_name="Total")),
                ("date_and_time", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CustomerCL.customer",
                    ),
                ),
                ("product", models.ManyToManyField(to="ProductCL.product")),
            ],
        ),
    ]
